/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AScrollbar: typeof import('@arco-design/web-vue/es')['Scrollbar']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    Chart: typeof import('./src/components/Chart/index.vue')['default']
    GlobalSetting: typeof import('./src/components/global-setting/index.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    PageWrap: typeof import('./src/components/PageWrap/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
